name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  zard_darto_middleware:
    path: ../
  darto: ^0.0.21
  zard: ^0.0.11

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
