name: zard_darto_middleware
description: Validation middleware for Darto using Zard.
version: 0.0.3
homepage: https://github.com/evandersondev/zard_darto_middleware

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  darto_types: ^0.0.1
  zard: ^0.0.17

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.2
