name: zard_darto_middleware
description: Validation middleware for Darto using Zard.
version: 0.0.1
homepage: https://github.com/evandersondev/zard_darto_middleware

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  darto: ^0.0.21
  zard: ^0.0.12

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
